/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DigitalNomadConciergeCapeTownRouteImport } from './routes/digital-nomad-concierge-cape-town'
import { Route as EventPlanningRouteImport } from './routes/event-planning'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ScoutedImagesDatabaseRouteImport } from './routes/scouted-images-database'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalNomadConciergeCapeTownRoute =
  DigitalNomadConciergeCapeTownRouteImport.update({
    id: '/digital-nomad-concierge-cape-town',
    path: '/digital-nomad-concierge-cape-town',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventPlanningRoute = EventPlanningRouteImport.update({
  id: '/event-planning',
  path: '/event-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutedImagesDatabaseRoute = ScoutedImagesDatabaseRouteImport.update({
  id: '/scouted-images-database',
  path: '/scouted-images-database',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digital-nomad-concierge-cape-town': typeof DigitalNomadConciergeCapeTownRoute
  '/event-planning': typeof EventPlanningRoute
  '/mcp': typeof McpRoute
  '/scouted-images-database': typeof ScoutedImagesDatabaseRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digital-nomad-concierge-cape-town': typeof DigitalNomadConciergeCapeTownRoute
  '/event-planning': typeof EventPlanningRoute
  '/mcp': typeof McpRoute
  '/scouted-images-database': typeof ScoutedImagesDatabaseRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digital-nomad-concierge-cape-town': typeof DigitalNomadConciergeCapeTownRoute
  '/event-planning': typeof EventPlanningRoute
  '/mcp': typeof McpRoute
  '/scouted-images-database': typeof ScoutedImagesDatabaseRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/digital-nomad-concierge-cape-town'
    | '/event-planning'
    | '/mcp'
    | '/scouted-images-database'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/digital-nomad-concierge-cape-town'
    | '/event-planning'
    | '/mcp'
    | '/scouted-images-database'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/digital-nomad-concierge-cape-town'
    | '/event-planning'
    | '/mcp'
    | '/scouted-images-database'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalNomadConciergeCapeTownRoute: typeof DigitalNomadConciergeCapeTownRoute
  EventPlanningRoute: typeof EventPlanningRoute
  McpRoute: typeof McpRoute
  ScoutedImagesDatabaseRoute: typeof ScoutedImagesDatabaseRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-nomad-concierge-cape-town': {
      id: '/digital-nomad-concierge-cape-town'
      path: '/digital-nomad-concierge-cape-town'
      fullPath: '/digital-nomad-concierge-cape-town'
      preLoaderRoute: typeof DigitalNomadConciergeCapeTownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-planning': {
      id: '/event-planning'
      path: '/event-planning'
      fullPath: '/event-planning'
      preLoaderRoute: typeof EventPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouted-images-database': {
      id: '/scouted-images-database'
      path: '/scouted-images-database'
      fullPath: '/scouted-images-database'
      preLoaderRoute: typeof ScoutedImagesDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalNomadConciergeCapeTownRoute: DigitalNomadConciergeCapeTownRoute,
  EventPlanningRoute: EventPlanningRoute,
  McpRoute: McpRoute,
  ScoutedImagesDatabaseRoute: ScoutedImagesDatabaseRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
