/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DigitalNomadConciergeCapeTownRouteImport } from './routes/digital-nomad-concierge-cape-town'
import { Route as IndexRouteImport } from './routes/index'

const DigitalNomadConciergeCapeTownRoute =
  DigitalNomadConciergeCapeTownRouteImport.update({
    id: '/digital-nomad-concierge-cape-town',
    path: '/digital-nomad-concierge-cape-town',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digital-nomad-concierge-cape-town': typeof DigitalNomadConciergeCapeTownRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digital-nomad-concierge-cape-town': typeof DigitalNomadConciergeCapeTownRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digital-nomad-concierge-cape-town': typeof DigitalNomadConciergeCapeTownRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/digital-nomad-concierge-cape-town'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/digital-nomad-concierge-cape-town'
  id: '__root__' | '/' | '/digital-nomad-concierge-cape-town'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalNomadConciergeCapeTownRoute: typeof DigitalNomadConciergeCapeTownRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/digital-nomad-concierge-cape-town': {
      id: '/digital-nomad-concierge-cape-town'
      path: '/digital-nomad-concierge-cape-town'
      fullPath: '/digital-nomad-concierge-cape-town'
      preLoaderRoute: typeof DigitalNomadConciergeCapeTownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalNomadConciergeCapeTownRoute: DigitalNomadConciergeCapeTownRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
